<%@ Page Title="" Language="C#" MasterPageFile="~/Dashboard/Site.Master" AutoEventWireup="true" CodeBehind="Categories.aspx.cs" Inherits="LabManagement.Dashboard.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="form1" runat="server">
        <div class="container">
        <h2>Categories</h2>
        <div class="category-form">
            <h3>Create New Category</h3>
            <div>
                <label for="cName">Category Name:</label>
                <asp:TextBox ID="cName" runat="server" type="text" required="true"></asp:TextBox>
                <label for="cDec">Description:</label>
                <asp:TextBox ID="cDec" runat="server" type="text" TextMode="MultiLine" required="true"></asp:TextBox>
                <asp:Button ID="insertBtn" runat="server" OnClick="insertData" Text="Create"/>
            </div>
        </div>
         <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="id" AllowPaging="True" OnPageIndexChanging="OnPageIndexChanging" PageSize="25" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="Empty" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" InsertVisible="False" ReadOnly="True">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="lastUpdate" HeaderText="lastUpdate" SortExpression="lastUpdate" InsertVisible="False" ReadOnly="True">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                </Columns>

                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />

            </asp:GridView>
    </div>
    </form>
</asp:Content>
