<%@ Page Title="" Language="C#" MasterPageFile="~/Dashboard/Site.Master" AutoEventWireup="true" CodeBehind="Categories.aspx.cs" Inherits="LabManagement.Dashboard.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style>
        .Holder {
            padding: 1rem;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            gap: 0.5rem;
        }

        .catForm {
            width: 60vw;
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
            padding: 1rem;
            background-color: #fff;
            border-radius: 1rem;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1), 0 6px 8px rgba(0, 0, 0, 0.1);
        }

        .catCont{
            display: flex;
            flex-direction: column;
        }

        .catCont #cName, #cDec{
            width: 40vw;
            margin-bottom: 10px;
        }
        .table-sm {}
    </style>
    <div class="Holder">
        <div class="catForm">
            <div class="catCont">
                <label for="cName">Category Name:</label>
                <asp:TextBox ID="cName" runat="server" type="text" required="true"></asp:TextBox>
                <label for="cDec">Description:</label>
                <asp:TextBox ID="cDec" runat="server" type="text" TextMode="MultiLine" required="true"></asp:TextBox>
                <asp:Button ID="insertBtn" runat="server" OnClick="insertData" Text="Create" />
            </div>
        </div>
        <asp:GridView ID="gridview" Width="100%" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="id" AllowPaging="True" PageSize="25" EmptyDataText="Empty" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource1">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" InsertVisible="False" ReadOnly="True">
                    <HeaderStyle></HeaderStyle>

                </asp:BoundField>
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name">
                    <HeaderStyle></HeaderStyle>

                </asp:BoundField>
                <asp:BoundField DataField="description" HeaderText="description" SortExpression="description">
                    <HeaderStyle></HeaderStyle>

                </asp:BoundField>
                <asp:BoundField DataField="lastUpdate" HeaderText="lastUpdate" SortExpression="lastUpdate">
                    <HeaderStyle></HeaderStyle>

                </asp:BoundField>
            </Columns>

            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />

        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnString %>" SelectCommand="SELECT * FROM Tbl_Categories" DeleteCommand="Delete From Tbl_Categories where id = @id" UpdateCommand="UPDATE Tbl_Categories SET name = @name, description = @description,lastUpdate = @lastUpdate WHERE id=@id"></asp:SqlDataSource>
    </div>
</asp:Content>
