<%@ Page Title="" Language="C#" MasterPageFile="~/Dashboard/Site.Master" AutoEventWireup="true" CodeBehind="Inventory.aspx.cs" Inherits="LabManagement.Dashboard.WebForm2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="form1" runat="server">
        <div class="container">
            <div class="category-form">
            <h3>Create New Category</h3>
            <div>
                <label for="code">Code:</label>
                <asp:TextBox ID="code" runat="server" type="text" required="true"></asp:TextBox>

                <label for="name">Name:</label>
                <asp:TextBox ID="name" runat="server" type="text" required="true"></asp:TextBox>

                <label for="category">Category:</label>
                <asp:DropDownList ID="ddCat" runat="server" AutoPostBack="false" OnSelectedIndexChanged="ddCat_SelectedIndexChanged">
						<asp:ListItem>Select Category</asp:ListItem>
					</asp:DropDownList>
                
                <label for="supplier">Supplier:</label>
                <asp:TextBox ID="supplier" runat="server" type="text" required="true"></asp:TextBox>
                
                <label for="quantity">Quantity:</label>
                <asp:TextBox ID="quantity" runat="server" type="text" required="true"></asp:TextBox>
                
                <label for="pPrice">Purchase Price:</label>
                <asp:TextBox ID="pPrice" runat="server" type="text" required="true"></asp:TextBox>

                <label for="avilable">Avilable:</label>
                <asp:TextBox ID="avilable" runat="server" type="text" required="true"></asp:TextBox>

                <label for="eDate">Expiration Date:</label>
                <asp:TextBox ID="eDate" runat="server" type="text" required="true"></asp:TextBox>
                
                <asp:Button ID="insertBtn" runat="server" OnClick="insertData" Text="Create"/>
            </div>
        </div>
            <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="id" AllowPaging="True" OnPageIndexChanging="OnPageIndexChanging" PageSize="25" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="Empty" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="id" SortExpression="id">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="code" HeaderText="code" SortExpression="code">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="category" HeaderText="category" SortExpression="category">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="supplier" HeaderText="supplier" SortExpression="supplier">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="quantity" HeaderText="quantity" SortExpression="quantity">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="purchesePrice" HeaderText="purchesePrice" SortExpression="purchesePrice">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="available" HeaderText="available" SortExpression="available">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="expirationDate" HeaderText="expirationDate" SortExpression="expirationDate">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                    <asp:BoundField DataField="lastUpdate" HeaderText="lastUpdate" SortExpression="lastUpdate">
                        <HeaderStyle></HeaderStyle>

                    </asp:BoundField>
                </Columns>

                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />

            </asp:GridView>
        </div>
    </form>
</asp:Content>
